pipeline {
    agent none
    stages {

		stage('Stage 1') {
            steps {
                echo 'Hello world!' 
				}
         }
        stage('Back-end') {
            agent {
                docker { image 'maven:3-alpine' }
            }
            steps {
                sh 'mvn --version'
            }
        }
        stage('Front-end') {
            agent {
                docker { image 'node:7-alpine' }
            }
            steps {
                sh 'node --version'
				sh 'sleep 10'
            }
		}
	}
}
