pipeline {
    agent none
    stages {
        stage('Back-end') {
            agent {
                docker { image 'maven:3-alpine' }
            }
            steps {
                sh 'mvn --version'
            }
        }
        stage('Front-end') {
            agent {
                docker { image 'node:7-alpine' }
            }
            steps {
                sh 'node --version'
				sh 'sleep 10'
            }
        }
		stage ('freestyle-01'){
					agent{
				  build job: 'freestyle-01', wait: false
				  }
		    }
	    }
}


