pipeline {
    agent any

    stages {
		stage ('War Deployment Stage') {

            steps {
                withMaven(maven : 'maven_3_5_0') {
                    sh 'mvn -f war-sample/pom.xml  deploy'
                }
            }
		}
	}
}